import { db, isConfigured } from "./firebase.js";
import { doc, getDoc } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js";
const $ = selector => document.querySelector(selector);
const labels = { novo: "Recebido", em_analise: "Em análise", orcamento_enviado: "Orçamento enviado", aprovado: "Aprovado", em_manutencao: "Em manutenção", pronto: "Pronto para retirada", entregue: "Entregue", cancelado: "Cancelado" };
$("#trackPhone").addEventListener("input", event => { const digits = event.target.value.replace(/\D/g, "").slice(0, 11); event.target.value = digits.length > 10 ? digits.replace(/(\d{2})(\d{5})(\d{0,4})/, "($1) $2-$3") : digits.replace(/(\d{2})(\d{0,5})(\d{0,4})/, (_, a,b,c) => b ? `(${a}) ${b}${c ? `-${c}` : ""}` : a); });
async function trackingId(phone) { const value = phone.replace(/\D/g, ""); if (globalThis.crypto?.subtle) { const digest = await globalThis.crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)); return [...new Uint8Array(digest)].map(byte => byte.toString(16).padStart(2, "0")).join(""); } let hash = 0x811c9dc5; for (const character of value) { hash ^= character.charCodeAt(0); hash = Math.imul(hash, 0x01000193); } return `legacy-${(hash >>> 0).toString(16).padStart(8, "0")}`; }
function setMessage(text) { const el = $("#trackMessage"); el.textContent = text; el.className = "message error"; }
function formatDate(value) { return value ? new Date(`${value}T12:00:00`).toLocaleDateString("pt-BR") : "A definir"; }
function formatValue(value) { return value == null ? "Aguardando avaliação" : Number(value).toLocaleString("pt-BR", { style: "currency", currency: "BRL" }); }
$("#trackForm").addEventListener("submit", async event => { event.preventDefault(); if (!isConfigured) return setMessage("O sistema ainda não está configurado."); const phone = $("#trackPhone").value.trim(); if (!phone) return setMessage("Informe o telefone usado na solicitação."); const button = $("#trackButton"); button.disabled = true; button.firstChild.textContent = "Consultando... "; $("#trackResult").classList.add("hidden"); try { const snapshot = await getDoc(doc(db, "acompanhamentos", await trackingId(phone))); const pedidos = snapshot.exists() ? snapshot.data().pedidos || [] : []; if (!pedidos.length) return setMessage("Não encontramos atendimentos para este telefone."); $("#resultsList").innerHTML = pedidos.map(item => `<article class="track-order"><h2>${item.protocolo}</h2><p class="device">${item.aparelho}</p><div class="status-box"><small>SITUAÇÃO ATUAL</small><strong>${labels[item.status] || item.status}</strong></div><div class="result-info"><div><small>VALOR DO ORÇAMENTO</small><strong>${formatValue(item.valor)}</strong></div><div><small>PREVISÃO DE ENTREGA</small><strong>${formatDate(item.previsaoEntrega)}</strong></div></div></article>`).join(""); $("#trackResult").classList.remove("hidden"); } catch (error) { console.error(error); setMessage("Não foi possível consultar agora. Tente novamente em instantes."); } finally { button.disabled = false; button.firstChild.textContent = "Consultar andamento "; } });
